# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1d8da96531ee31dae7e51859f8ecf3754633035d97b469f5184aeeb53eddc1c1fffadced9be8293a891e2db7d392fb9486471712f86e0973b93c74b88335d7d

test:
  secret_key_base: a7eace8f16506c323c4f56eaa876ac99488609c3b3a0bc4794e813c7fc70b540d16312ff3fa86cc967e9cec3c381c2acac2f54da140f6878952c477142f5a29b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
